source 'http://rubygems.org'
gem 'guard'
gem 'guard-sass'
gem 'guard-coffeescript'
gem 'compass'
gem 'guard-concat'
gem 'guard-uglify'
gem 'nyulibraries-assets', github: 'NYULibraries/nyulibraries-assets', tag: 'v4.2.1'
